## Dataset correspondiente a la calidad del vino blanco, la variable a pronosticar es quality.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [2]:
df=pd.read_csv('data/winequality-white.csv', sep=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

Veamos un poco los datos

In [3]:
df.shape

(4898, 12)

In [4]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


### Dividamos en Train Test y Validation

- Proporción de 80/20 en ambos casos
- La columna quality es la y.
- Dividiremos primero en X_train,X_test,y_train,y_test
- Luego divido en X_train, y_train en los correspondientes Validation_train y Validation_test
- semilla 123


In [6]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(axis=1,columns='quality'),df['quality'],test_size=0.20,random_state=123)

In [7]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
4120            7.4              0.28         0.50            12.1      0.049   
1169            7.5              0.14         0.34             1.3      0.055   
1941            6.8              0.31         0.32             7.6      0.052   
1971            6.3              0.41         0.30             3.2      0.030   
3124            6.5              0.24         0.39            17.3      0.052   
...             ...               ...          ...             ...        ...   
1593            8.6              0.16         0.49             7.3      0.043   
4060            6.4              0.41         0.01             6.1      0.048   
1346            7.0              0.46         0.39             6.2      0.039   
3454            5.8              0.54         0.00             1.4      0.033   
3582            6.3              0.32         0.32             1.5      0.037   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
4120                 48.0                 122.0  0.99730  3.01       0.44   
1169                 50.0                 153.0  0.99450  3.29       0.80   
1941                 35.0                 143.0  0.99590  3.14       0.38   
1971                 49.0                 164.0  0.99270  3.53       0.79   
3124                 22.0                 126.0  0.99888  3.11       0.47   
...                   ...                   ...      ...   ...        ...   
1593                  9.0                  63.0  0.99530  3.13       0.59   
4060                 20.0                  70.0  0.99362  3.19       0.42   
1346                 46.0                 163.0  0.99280  3.21       0.35   
3454                 40.0                 107.0  0.98918  3.26       0.35   
3582                 12.0                  76.0  0.98993  3.30       0.46   

      alcohol  
4120      9.0  
1169      9.6  
1941      9.0  
1971     11.7  
3124      9.2  
...       ...  
1593     10.5  
4060     10.0  
1346     12.2  
3454     12.4  
3582     12.3  

[3918 rows x 11 columns]

In [8]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1088            7.4              0.20         0.37           16.95      0.048   
4366            5.9              0.29         0.28            3.20      0.035   
92              6.9              0.24         0.33            1.70      0.035   
2901            6.5              0.22         0.32            2.20      0.028   
2330            7.5              0.38         0.29           12.70      0.050   
...             ...               ...          ...             ...        ...   
4189            6.4              0.21         0.21            5.10      0.097   
3341            7.6              0.17         0.27            4.60      0.050   
1055            8.6              0.26         0.41            2.20      0.049   
3114            6.3              0.17         0.32            4.20      0.040   
654             6.5              0.21         0.37            2.50      0.048   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1088                 43.0                 190.0  0.99950  3.03       0.42   
4366                 16.0                 117.0  0.98959  3.26       0.42   
92                   47.0                 136.0  0.99000  3.26       0.40   
2901                 36.0                  92.0  0.99076  3.27       0.59   
2330                 25.0                 209.0  0.99860  3.25       0.59   
...                   ...                   ...      ...   ...        ...   
4189                 21.0                 105.0  0.99390  3.07       0.46   
3341                 23.0                  98.0  0.99422  3.08       0.47   
1055                 29.0                 111.0  0.99410  2.96       0.44   
3114                 37.0                 117.0  0.99182  3.24       0.43   
654                  70.0                 138.0  0.99170  3.33       0.75   

      alcohol  
1088      9.2  
4366     12.6  
92       12.6  
2901     11.9  
2330      9.3  
...       ...  
4189      9.6  
3341      9.5  
1055     10.0  
3114     11.3  
654      11.4  

[980 rows x 11 columns]

### Estandaricemos:

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

# creamos el "estandarizador"
t_estandard=("estandarizador",StandardScaler(),X_train.columns)

# lo ubicamos en un transformador de columnas, en este caso sólo estandarizamos, pero vamos a hacerlo de todas maneras.
transformador_columnas = ColumnTransformer(transformers=[t_estandard]) #,remainder='passthrough')
# lo entrenamos con fit. Simplmente calcula la media y el desvio de los datos que le pasamos
transformador_columnas.fit(X_train)
# lo aplicamos
X_train_transformado=transformador_columnas.transform(X_train)
X_test_transformad=transformador_columnas.transform(X_test)


''

In [12]:
X_train_transformado.shape

(3918, 11)

In [13]:
X_train_transformado

array([[ 0.65613633,  0.0068221 ,  1.35059928, ..., -1.17444696,
        -0.43711777, -1.21973817],
       [ 0.77529007, -1.38427848,  0.04474501, ...,  0.67789546,
         2.70307718, -0.73094327],
       [-0.05878617,  0.30491509, -0.11848678, ..., -0.31443084,
        -0.9604836 , -1.21973817],
       ...,
       [ 0.17952133,  1.79538   ,  0.45282447, ...,  0.14865477,
        -1.22216651,  1.38716796],
       [-1.25032365,  2.59029462, -2.73019533, ...,  0.4794302 ,
        -1.22216651,  1.5500996 ],
       [-0.65455491,  0.40427941, -0.11848678, ...,  0.74405055,
        -0.2626625 ,  1.46863378]])

### Validation

In [14]:
Xval_train,Xval_test,yval_train,yval_test=train_test_split(X_train,y_train,test_size=0.20,random_state=123)

### Estandarización del Validation

In [16]:
transformador_columnas.fit(Xval_train)
# lo aplico
Xval_train_transformado=transformador_columnas.transform(Xval_train)
Xval_test_transformado=transformador_columnas.transform(Xval_test)


''

In [17]:
Xval_train_transformado

array([[ 0.18841434,  0.39579517, -0.76699665, ...,  0.27635787,
         1.13926502, -0.88484946],
       [-0.28721236, -0.59761536, -0.84974822, ..., -0.70897269,
        -0.26418186, -1.371943  ],
       [ 0.06950767,  1.5878878 ,  0.72253154, ...,  0.86755621,
        -0.26418186, -0.80366721],
       ...,
       [-0.04939901,  0.89250043, -0.43599038, ...,  0.27635787,
        -0.26418186,  1.55061822],
       [ 1.02076106,  0.69381833,  1.05353781, ..., -2.15412419,
        -0.17646643, -1.20957849],
       [ 0.18841434, -1.59102589, -1.18075448, ...,  0.6704901 ,
        -0.70275901, -0.88484946]])

## Comparación de modelos (en el validation)

In [18]:
from sklearn.metrics import mean_squared_error, r2_score

### Ridge

In [19]:
from sklearn.linear_model import Ridge

In [20]:
modelo_ridge=Ridge(alpha=1)
modelo_ridge.fit(Xval_train_transformado,yval_train)
R2_Ridge=modelo_ridge.score(Xval_test_transformado,yval_test)

print("EVALUACIÓN del modelo de Regresión Lineal: ")
print("R2_Ridge: ",round(R2_Ridge,3)) # evaluamos el modelo
y_pred_Ridge = modelo_ridge.predict(Xval_test_transformado)

RMSE_Ridge=mean_squared_error(yval_test, y_pred_Ridge,squared=False)

Promedio_yval_test=np.mean(yval_test)

print("Promedio de yval_test= ",round(Promedio_yval_test,3) )
print("RMSE_Ridge: ",round(RMSE_Ridge,3))
print("RMSE/prom(y) %=",round(RMSE_Ridge/Promedio_yval_test*100,3))

EVALUACIÓN del modelo de Regresión Lineal: 
R2_Ridge:  0.293
Promedio de yval_test=  5.911
RMSE_Ridge:  0.759
RMSE/prom(y) %= 12.846


### Lasso

In [21]:
from sklearn.linear_model import Lasso

modelo_lasso= Lasso(alpha=0)
modelo_lasso.fit(Xval_train_transformado,yval_train)
modelo_lasso.score(Xval_test_transformado,yval_test)

C:\Users\AI\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  after removing the cwd from sys.path.
C:\Users\AI\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
C:\Users\AI\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 891.6557132635833, tolerance: 0.2444944798978942
  positive)


0.2935748872077719

In [22]:
from sklearn.linear_model import LogisticRegression

### Regresión lógistica Ridge (penalización l2)

In [23]:
Log_Ridge=LogisticRegression(penalty='l2', C=100, max_iter=1000, multi_class='ovr')
Log_Ridge.fit(Xval_train_transformado,yval_train)
Log_Ridge.score(Xval_test_transformado,yval_test)

0.5280612244897959

### Lasso

In [24]:
Log_Lasso=LogisticRegression(penalty='l1', solver='saga',C=1, max_iter=10000, multi_class='ovr')  # tuve que aumentar max_iter
Log_Lasso.fit(Xval_train_transformado,yval_train)
Log_Lasso.score(Xval_test_transformado,yval_test)

0.5306122448979592

In [25]:
Log_Lasso.coef_

array([[ 0.78439383,  0.26419192, -0.12298385, -0.00623975,  0.25773341,
         0.59152818, -0.2029266 ,  0.        ,  0.26580264, -0.16487354,
         0.        ],
       [ 0.12388573,  0.51099281, -0.06270744, -1.11389722, -0.02225345,
        -0.77932447, -0.103544  ,  0.83029304, -0.07112852, -0.00752964,
        -0.31181662],
       [ 0.        ,  0.39033323,  0.01437336, -0.38689413, -0.02870699,
        -0.12115912,  0.12690371,  0.20236954, -0.08078047, -0.16615656,
        -1.04649158],
       [-0.13153921, -0.35780363,  0.02293731,  0.        ,  0.03256005,
         0.00778231,  0.00643371,  0.25496581, -0.04422999, -0.01856398,
         0.33447659],
       [ 0.3775905 , -0.40868748, -0.08497125,  1.19753349, -0.2822724 ,
         0.07504204,  0.        , -1.63048215,  0.3898384 ,  0.24856303,
         0.16543086],
       [ 0.08751533, -0.32651275, -0.07912728,  0.71546186,  0.07045703,
         0.30169159, -0.20044492, -0.53645073,  0.15074843,  0.12145812,
         0.752

In [26]:
df.quality.unique()

array([6, 5, 7, 8, 4, 3, 9], dtype=int64)