# Ejercicio 2 SVM

In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('data/winequality-white.csv', sep=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

Pronosticar quality, problema de clasificación. 

In [7]:
from sklearn.model_selection import train_test_split

X=df.drop(axis=1,columns='quality')
y=df['quality']

#Train / Test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=123)

# Validation
Xval_train,Xval_test,yval_train,yval_test=train_test_split(X_train,y_train,test_size=0.20,random_state=123)

In [8]:
from sklearn.svm import SVC

## SVM Lineal

In [9]:
for c in [0.01,0.1,1,10,100]    
    
    svm=SVC(C=c, kernel='linear')
    svm.fit(Xval_train,yval_train)
    acc=svm.score(Xval_test,yval_test)

    print("Kernel:linear")
    print("C: ",c)
    print("Accuracy: ",acc)

0.5127551020408163


## SVM polinómico grado 2

In [12]:
for c in [10,100,1000, 10000]:    
    
    svm=SVC(C=c, kernel='poly',degree=2)
    svm.fit(Xval_train,yval_train)
    acc=svm.score(Xval_test,yval_test)
    
    print("--------------------------------")
    print("Kernel:poly, grado 2")
    print("C: ",c)
    print("Accuracy: ",acc)

Kernel:poly, grado 2
C:  10
Accuracy:  0.4413265306122449
Kernel:poly, grado 2
C:  100
Accuracy:  0.45408163265306123
Kernel:poly, grado 2
C:  1000
Accuracy:  0.48214285714285715
Kernel:poly, grado 2
C:  10000
Accuracy:  0.5038265306122449


Seguir probando!

## SVM polinómico grado 3

In [13]:
for c in [10,100,1000, 10000]:    
    
    svm=SVC(C=c, kernel='poly',degree=3)
    svm.fit(Xval_train,yval_train)
    acc=svm.score(Xval_test,yval_test)
    
    print("--------------------------------")
    print("Kernel:poly, grado 3")
    print("C: ",c)
    print("Accuracy: ",acc)

--------------------------------
Kernel:poly, grado 3
C:  10
Accuracy:  0.4477040816326531
--------------------------------
Kernel:poly, grado 3
C:  100
Accuracy:  0.4489795918367347
--------------------------------
Kernel:poly, grado 3
C:  1000
Accuracy:  0.475765306122449
--------------------------------
Kernel:poly, grado 3
C:  10000
Accuracy:  0.49362244897959184


## SVM polinómico grado 4

In [14]:
for c in [10,100,1000, 10000]:    
    
    svm=SVC(C=c, kernel='poly',degree=4)
    svm.fit(Xval_train,yval_train)
    acc=svm.score(Xval_test,yval_test)
    
    print("--------------------------------")
    print("Kernel:poly, grado 4")
    print("C: ",c)
    print("Accuracy: ",acc)

--------------------------------
Kernel:poly, grado 4
C:  10
Accuracy:  0.45408163265306123
--------------------------------
Kernel:poly, grado 4
C:  100
Accuracy:  0.45790816326530615
--------------------------------
Kernel:poly, grado 4
C:  1000
Accuracy:  0.4744897959183674
--------------------------------
Kernel:poly, grado 4
C:  10000
Accuracy:  0.4770408163265306


## SVM rbf

In [15]:
for c in [1,10,100,1000, 10000]:    
    
    svm=SVC(C=c, kernel='rbf')
    svm.fit(Xval_train,yval_train)
    acc=svm.score(Xval_test,yval_test)
    
    print("--------------------------------")
    print("Kernel:rbf")
    print("C: ",c)
    print("Accuracy: ",acc)

--------------------------------
Kernel:rb
C:  1
Accuracy:  0.44005102040816324
--------------------------------
Kernel:rb
C:  10
Accuracy:  0.44260204081632654
--------------------------------
Kernel:rb
C:  100
Accuracy:  0.4732142857142857
--------------------------------
Kernel:rb
C:  1000
Accuracy:  0.475765306122449
--------------------------------
Kernel:rb
C:  10000
Accuracy:  0.49362244897959184


## SVM con kernel Sigmoide

In [17]:
for c in [0.01,0.1,1,10,100]:    
    
    svm=SVC(C=c, kernel='sigmoid')
    svm.fit(Xval_train,yval_train)
    acc=svm.score(Xval_test,yval_test)
    
    print("--------------------------------")
    print("Kernel: sigmoide")
    print("C: ",c)
    print("Accuracy: ",acc)

--------------------------------
Kernel: sigmoide
C:  0.01
Accuracy:  0.43494897959183676
--------------------------------
Kernel: sigmoide
C:  0.1
Accuracy:  0.35586734693877553
--------------------------------
Kernel: sigmoide
C:  1
Accuracy:  0.41581632653061223
--------------------------------
Kernel: sigmoide
C:  10
Accuracy:  0.4119897959183674
--------------------------------
Kernel: sigmoide
C:  100
Accuracy:  0.39540816326530615


## Modelo Seleccionado

- Kernel Lineal. C:1

## Evaluación del modelo  elegido

En train / test

In [22]:
svm_eval=SVC(C=1, kernel='linear',probability=True)
svm_eval.fit(X_train,y_train)
acc=svm_eval.score(X_test,y_test)

print("Kernel:linear")
print("C: ",1)
print("Accuracy: ",acc)

Kernel:linear
C:  1
Accuracy:  0.5459183673469388


In [28]:
# Si queremos ver las probabilidades para cada clase:
np.set_printoptions(threshold=np.inf)
np.round(svm_eval.predict_proba(X_train),3)

array([[0.004, 0.016, 0.522, 0.395, 0.051, 0.012, 0.   ],
       [0.005, 0.014, 0.264, 0.547, 0.152, 0.017, 0.001],
       [0.004, 0.033, 0.638, 0.294, 0.026, 0.006, 0.   ],
       [0.009, 0.012, 0.097, 0.329, 0.49 , 0.062, 0.002],
       [0.003, 0.013, 0.382, 0.52 , 0.068, 0.013, 0.   ],
       [0.003, 0.012, 0.044, 0.377, 0.485, 0.077, 0.001],
       [0.004, 0.005, 0.533, 0.408, 0.044, 0.006, 0.   ],
       [0.004, 0.005, 0.638, 0.326, 0.024, 0.004, 0.   ],
       [0.004, 0.048, 0.179, 0.489, 0.236, 0.043, 0.001],
       [0.007, 0.006, 0.063, 0.494, 0.364, 0.066, 0.002],
       [0.005, 0.018, 0.289, 0.535, 0.141, 0.013, 0.001],
       [0.007, 0.024, 0.489, 0.373, 0.087, 0.019, 0.001],
       [0.005, 0.059, 0.341, 0.486, 0.091, 0.016, 0.001],
       [0.004, 0.007, 0.623, 0.342, 0.021, 0.002, 0.   ],
       [0.004, 0.006, 0.062, 0.423, 0.428, 0.075, 0.001],
       [0.004, 0.002, 0.031, 0.461, 0.44 , 0.061, 0.001],
       [0.004, 0.013, 0.552, 0.389, 0.038, 0.005, 0.   ],
       [0.005,

In [25]:
svm_eval.predict(X_train)

array([5, 6, 5, ..., 6, 6, 6])

In [27]:
y.unique()

array([6, 5, 7, 8, 4, 3, 9])

## Modelo de Producción

In [20]:
svm_eval=SVC(C=1, kernel='linear')
svm_eval.fit(X,y)

SVC(C=1, kernel='linear')

In [21]:
# guardar el modelo con pickle