In [2]:
import numpy as np

In [31]:
calificaciones=np.load("data/ratings_movie_lens.npy")
cali_1 = calificaciones
calificaciones

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [4]:
calificaciones[0:1],calificaciones[942,1]

(array([[5., 3., 4., ..., 0., 0., 0.]]), 5.0)

In [5]:
calificaciones.shape
q_usuarios = 943
q_peliculas = 1682

In [6]:
np.sum(calificaciones>0)

100000

In [9]:
a = np.array(np.sum(calificaciones>0,axis=1))

In [7]:
q_calificaciones_reales = np.sum(calificaciones>0)

In [10]:
q_users_10 = a[:10]
q_users_10

array([272,  62,  54,  24, 175, 211, 403,  59,  22, 184])

In [17]:
#q_promedio_pelis_xusuario = q_calificaciones_reales/q_usuarios
q_promedio_pelis_xusuario = np.mean(np.array(np.sum(calificaciones>0,axis=1)))
q_promedio_pelis_xusuario

106.04453870625663

In [140]:
np.array(np.sum(calificaciones>0,axis=0))

array([452, 131,  90, ...,   1,   1,   1])

In [141]:
q_calif_10_pelis = np.array(np.sum(calificaciones>0,axis=0)[:10])
q_calif_10_pelis

array([452, 131,  90, 209,  86,  26, 392, 219, 299,  89])

### calcular la calificación promedio para cada una de las películas utilizando para ello las calificaciones válidas.  

In [26]:
calificacionesNAN = calificaciones
calificacionesNAN[calificacionesNAN==0]=np.nan

d=np.nanmean(calificacionesNAN,axis=0)
d
#(use NAN porque tener valores iguales a cero afectaria el promedio real)

array([3.87831858, 3.20610687, 3.03333333, ..., 2.        , 3.        ,
       3.        ])

In [21]:
best_mean_rating = np.nanmax(np.nanmean(calificacionesNAN,axis=0))
best_mean_rating
#(el promedio no es tan representativo, ya que la pelicula cuenta con la calificacion de un solo usuario)

5.0

In [22]:
id_best_mean_rating = np.argmax(np.nanmean(calificacionesNAN,axis=0))

In [23]:
best_mean_rating,id_best_mean_rating

(5.0, 813)

In [27]:
e = np.array(d>=3)
np.sum(e==0,axis=0)

628

In [32]:
prom = np.nanmean(calificacionesNAN)
ratingsDamped = np.where(cali_1==0,prom,cali_1)
means=np.mean(ratingsDamped,axis=0)

ratingsDamped,means

(array([[5.     , 3.     , 4.     , ..., 3.52986, 3.52986, 3.52986],
        [4.     , 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        [3.52986, 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        ...,
        [5.     , 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        [3.52986, 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        [3.52986, 5.     , 3.52986, ..., 3.52986, 3.52986, 3.52986]]),
 array([3.69688363, 3.48488475, 3.48247145, ..., 3.52823767, 3.52929811,
        3.52929811]))

In [33]:
best_damped_rating = np.max(means)

id_best_damped_rating = np.argmax(means)

In [34]:
ratingsDamped,best_damped_rating,id_best_damped_rating

(array([[5.     , 3.     , 4.     , ..., 3.52986, 3.52986, 3.52986],
        [4.     , 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        [3.52986, 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        ...,
        [5.     , 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        [3.52986, 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
        [3.52986, 5.     , 3.52986, ..., 3.52986, 3.52986, 3.52986]]),
 4.042152279957607,
 49)

In [42]:
dam = np.array(means>=3)
q_damped_3 = np.sum(dam==1,axis=0)
q_damped_3
#(todos los valores iguales a "nan" fueron igualados al promedio)

1682

Cargue el vector vec_decay:

In [35]:
vec_decay=np.load("data/vec_decay.npy") 
vec_decay

array([0.84823459, 0.64306967, 0.61342573, ..., 0.50813415, 0.86873329,
       0.72372801])

In [36]:
calificaciones

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [37]:
calificaciones_decay = vec_decay*calificaciones
calificaciones_decay2 = calificaciones_decay
calificaciones_decay2

array([[4.24117296, 1.929209  , 2.45370291, ..., 0.        , 0.        ,
        0.        ],
       [3.39293837, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [4.24117296, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.21534834, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [47]:

calificaciones_decay[calificaciones_decay==0]=np.nan

prom_cali_decay_nan = np.nanmean(calificaciones_decay)


decay_damped = np.where((vec_decay*calificaciones)==0,prom_cali_decay_nan,(vec_decay*calificaciones))


In [48]:
calificaciones_decay = vec_decay*calificaciones
best_decay_damped = np.max(decay_damped)
best_decay_damped

4.99868543324212

In [49]:
pd = np.mean(decay_damped,axis=0)
id_best_decay_damped = np.argmax(pd)
id_best_decay_damped

173

In [12]:
q_usuarios

943

In [13]:
q_peliculas

1682

In [14]:
q_calificaciones_reales

100000

In [15]:
q_users_10

array([272,  62,  54,  24, 175, 211, 403,  59,  22, 184])

In [18]:
q_promedio_pelis_xusuario

106.04453870625663

In [155]:
q_calif_10_pelis

array([452, 131,  90, 209,  86,  26, 392, 219, 299,  89])

### PROBLEMA 1

In [28]:
best_mean_rating

5.0

In [157]:
id_best_mean_rating

813

### PROBLEMA 2

In [38]:
ratingsDamped

array([[5.     , 3.     , 4.     , ..., 3.52986, 3.52986, 3.52986],
       [4.     , 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
       [3.52986, 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
       ...,
       [5.     , 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
       [3.52986, 3.52986, 3.52986, ..., 3.52986, 3.52986, 3.52986],
       [3.52986, 5.     , 3.52986, ..., 3.52986, 3.52986, 3.52986]])

In [159]:
best_damped_rating

4.042152279957607

In [39]:
id_best_damped_rating

49

In [43]:
q_damped_3

1682

### PROBLEMA 3

In [44]:
calificaciones_decay

array([[4.24117296, 1.929209  , 2.45370291, ..., 0.        , 0.        ,
        0.        ],
       [3.39293837, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [4.24117296, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.21534834, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [50]:
decay_damped

array([[4.24117296, 1.929209  , 2.45370291, ..., 2.66362531, 2.66362531,
        2.66362531],
       [3.39293837, 2.66362531, 2.66362531, ..., 2.66362531, 2.66362531,
        2.66362531],
       [2.66362531, 2.66362531, 2.66362531, ..., 2.66362531, 2.66362531,
        2.66362531],
       ...,
       [4.24117296, 2.66362531, 2.66362531, ..., 2.66362531, 2.66362531,
        2.66362531],
       [2.66362531, 2.66362531, 2.66362531, ..., 2.66362531, 2.66362531,
        2.66362531],
       [2.66362531, 3.21534834, 2.66362531, ..., 2.66362531, 2.66362531,
        2.66362531]])

In [164]:
best_decay_damped

4.99868543324212

In [51]:
id_best_decay_damped

173